name: $(Rev:r)
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: |
      $buildId = $env:BUILD_BUILDNUMBER.PadLeft(7, '0');
      $versionSuffixPR = "ci-$buildId-pr$($env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER)";
      $branchName = "$env:BUILD_SOURCEBRANCHNAME".Replace("_","");
      $versionSuffixBRANCH = "ci-$buildId";
      $isTag = "$env:BUILD_SOURCEBRANCH".StartsWith('refs/tags/');
      $isPR = "$env:SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" -ne ""
      $versionSuffix = if ($isTag) { "" } else { if ($isPR) { $versionSuffixPR } else { $versionSuffixBRANCH } };
      Write-Host "##vso[task.setvariable variable=VersionSuffix]$versionSuffix";
  - script: dotnet pack build.proj -v n
    displayName: Create package
    env:
      VersionSuffix: '$(VersionSuffix)'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'bin/nupkg'
      artifactName: 'nupkgs'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: dotnet pack build.proj -v n
    displayName: Create package
  
  - script: |
      docker network create kafka-net
      docker run -d --name zookeeper --network kafka-net --publish 2181:2181 zookeeper:3.4
      docker run -d --name kafka --network kafka-net --hostname localhost --publish 9092:9092 \
          --env KAFKA_ADVERTISED_HOST_NAME=127.0.0.1 --env ZOOKEEPER_IP=zookeeper \
          --env KAFKA_AUTO_CREATE_TOPICS_ENABLE=true \
          ches/kafka
      sleep 15
    displayName: Docker kafka for integration tests

  - script: dotnet test tests/Confluent.Kafka.FSharp.Tests -v n -f netcoreapp2.0 -c Release --logger:trx
    displayName: "Integration test"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
- job: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: echo "##vso[task.setvariable variable=FrameworkPathOverride]$(dirname $(which mono))/../lib/mono/4.5/"
    displayName: Workaround .NET reference assemblies on linux
  - script: dotnet pack build.proj -v n
    displayName: Create package
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: 'tests/**/*.trx'
    condition: succeededOrFailed()
